site_name: uniget docs
repo_url: https://github.com/uniget-org/cli
repo_name: uniget-org/cli
theme:
  name: material
  features:
  - navigation.sections
  palette:
    primary: indigo
    scheme: slate
nav:
- Home: index.md
- Usage:
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Global Parameters: global-parameters.md
  - Subcommands: subcommands.md
  - Environment: environment.md
  - Context: context.md
  - chroot: chroot.md
- Integrations:
  - Completion: completion.md
  - SystemD: systemd.md
  - Shell Profile: shell-profile.md
- Concepts:
  - Overview: concepts.md
  - Manifest: manifest.md
  - Authoring new tools: authoring.md
  - Docker: docker.md
  - Renovate: renovate.md
  - Caching: caching.md
  - Air-Gapped: air-gapped.md