site_name: uniget docs
repo_url: https://github.com/uniget-org/cli
repo_name: uniget-org/cli
theme:
  name: material
  features:
  - navigation.sections
  palette:
    primary: indigo
    scheme: slate
nav:
- Home: index.md
- Usage:
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Context: context.md
  - chroot: chroot.md
- Concepts:
  - Overview: concepts.md
  - Manifest: manifest.md
  - Docker: docker.md
  - Renovate: renovate.md
  - Air-Gapped: air-gapped.md